# Site settings
title: 智能感知实验室
email: hitszcv@163.com, hitszcv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 .
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://highcv.com" # the base hostname & protocol for your site
github_username:  hitszcv

# Build settings
markdown: kramdown
hightlighter: pygments
permalink: /:categories/:year-:month-:day-:title/
relative_permalinks: false