# Site settings
title: ComupterVision@HITSZ
email: hitszcv@163.com
description: > # this means to ignore newlines until "baseurl:"
 .
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://highcv.com" # the base hostname & protocol for your site
github_username:  hitszcv

# Build settings
markdown: kramdown
