# Site settings
title: 智能感知实验室
email: hitszcv@163.com, hitszcv@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 .
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://highcv.com" # the base hostname & protocol for your site
github_username:  hitszcv

# Build settings
markdown: kramdown
hightlighter: pygments
permalink: /:categories/:title/
relative_permalinks: false

scholar:
  style: ieee 
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template:  <abbr>{{reference}}</abbr><a href='{{link}}'>[pdf]</a>
  repository: ./repository
  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"